Updates to validator details for Helvetia Staking
nimiq/validators-api pull request #24
Opened 2024-11-17 20:36 UTC by joeleol

Updated: fee, payoutschedule and contact fields.

2024-11-17 23:07 UTC, onmax requested changes
Thank you!

2024-11-17 23:07 UTC, onmax commented on public/validators/main-albatross/NQ37 6EL5 BP9K XL1A 3ED0 L3EC NPR5 C9D3 BRKG.json
> +  "fee": 0.069,
nice

2024-11-17 23:07 UTC, onmax commented on public/validators/main-albatross/NQ37 6EL5 BP9K XL1A 3ED0 L3EC NPR5 C9D3 BRKG.json
> +    "discordInvitationUrl": "https://discord.com/channels/359979114062675969/1286574729989324810",
I tried to join to test it but I think is invalid.

Can you create the link as you are inviting someone to join? Thank you

you should see something like this:

![image](https://github.com/user-attachments/assets/5671091a-40cf-4d77-89c1-784d4e1c26d0)

2024-11-17 23:07 UTC, onmax commented on public/validators/main-albatross/NQ37 6EL5 BP9K XL1A 3ED0 L3EC NPR5 C9D3 BRKG.json
> +    "discordInvitationUrl": "https://discord.com/channels/359979114062675969/1286574729989324810",
Make sure to set the expiration date to never!

2024-11-17 23:07 UTC, onmax commented on public/validators/main-albatross/NQ37 6EL5 BP9K XL1A 3ED0 L3EC NPR5 C9D3 BRKG.json
> +  "payoutSchedule": "Every 360 batches (~6hrs)"
This test ideally will be shown to many type of users including beginner users.

Would you mind to rename it just to "Every 6 hours" to keep consistency with the rest of the validators?

thank you!

2024-11-17 23:58 UTC, Albermonte commented on public/validators/main-albatross/NQ37 6EL5 BP9K XL1A 3ED0 L3EC NPR5 C9D3 BRKG.json
> +    "discordInvitationUrl": "https://discord.com/channels/359979114062675969/1286574729989324810",
I think that's a link to the channel inside the Nimiq discord server, so the invitation link would be https://discord.gg/nimiq
There's no way to redirect to the channel if the user is not in the discord  server

2024-11-18 14:18 UTC, joeleol commented
Done, hopefully ok to merge now. Would be great to get this in pre-migration!

2024-11-18 15:43 UTC, onmax commented
Thank you!

2024-11-18 15:43 UTC, merged