add FRENCH NIMIQ VALIDATOR by Ju #1 & #2
nimiq/validators-api pull request #75
Opened 2024-12-03 18:37 UTC by Julien59247787

Hi, 

Just a little PR for the validation of my validators informations

Thank in advance and big thanks for all your great work on NIMIQ !

Ju

2024-12-04 14:00 UTC, Albermonte commented
The website needs to be a plubic reachable website, where your pool info is shown

2024-12-06 20:20 UTC, onmax commented
Hello. We have decided not to allow white background in the logo because it will look broken.

Here are some alternatives:

1. Use a background with more contrast
2. Remove the hexagon shape, as it essentially only cuts off a small part of the computer.

We would recommend the first, as we may need the hexagon shape in the future.

Please let me know if there is any convenient

Thanks for your understanding

2024-12-06 21:51 UTC, Julien59247787 commented
Hi Max,

Thank you for your feedback.

I understand and I’ll make the necessary modifications.

Removing the hexagon shape would be easier for me, but I’ll try to use a more contrasting background. However, I’ll have to remove the background from the image, which is harder because I don't have layers in this image.

PS: Could you tell me or give me the link to the documentation to help me build my own rewards management script, please? I can’t find an official one anywhere.

Thank you.

I’ll let you know.

Ju
De : Max ***@***.***>
Envoyé : vendredi 6 décembre 2024 21:21
À : nimiq/validators-api ***@***.***>
Cc : Julien CURTO ***@***.***>; Author ***@***.***>
Objet : Re: [nimiq/validators-api] add FRENCH NIMIQ VALIDATOR by Ju #1 & #2 (PR #75)


Hello. We have decided not to allow white background in the logo because it will look broken.

Here are some alternatives:

  1.  Use a background with more contrast
  2.  Remove the hexagon shape, as it essentially only cuts off a small part of the computer.

We would recommend the first, as we may need the hexagon shape in the future.

Please let me know if there is any convenient

Thanks for your understanding

—
Reply to this email directly, view it on GitHub<https://github.com/nimiq/validators-api/pull/75#issuecomment-2524087095>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AETGI66INEDUPY4DEXL26XL2EIBJTAVCNFSM6AAAAABS6NUKXGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRUGA4DOMBZGU>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2024-12-06 21:54 UTC, Julien59247787 commented
Hi Alberto,

Thank you for your reply.

I understand and I’ll make the necessary modifications.

The website is under construction for now, so I’ll just put the validator information again.

PS: Could you tell me or give me the link to the documentation to help me build my own rewards management script, please? I can’t find an official one anywhere.

Thank you.

I’ll let you know.

Ju

De : Alberto Monterroso ***@***.***>
Envoyé : mercredi 4 décembre 2024 15:01
À : nimiq/validators-api ***@***.***>
Cc : Julien CURTO ***@***.***>; Author ***@***.***>
Objet : Re: [nimiq/validators-api] add FRENCH NIMIQ VALIDATOR by Ju #1 & #2 (PR #75)


The website needs to be a plubic reachable website, where your pool info is shown

—
Reply to this email directly, view it on GitHub<https://github.com/nimiq/validators-api/pull/75#issuecomment-2517493107>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AETGI66NXYAVMRD22SLTXYT2D4DKBAVCNFSM6AAAAABS6NUKXGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMJXGQ4TGMJQG4>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2024-12-07 00:26 UTC, onmax commented
> Could you tell me or give me the link to the documentation to help me build my own rewards management script, please? I can’t find an official one anywhere.

We do not offer this kind of scripts at the moment. But feel free to join our validators' Telegram group to seek help in this reward from other pools.

If you are interested I can send you the link.

2024-12-09 18:23 UTC, Albermonte commented
If you dont have a public website, remove it from the json, thanks.

2024-12-10 14:07 UTC, Albermonte approved these changes

2024-12-10 14:10 UTC, Albermonte requested changes

2024-12-10 14:10 UTC, Albermonte commented on public/validators/main-albatross/NQ40 FC4D HAT6 9N1H P52H P4FX QL8P CE6Y 10VT.json
> +  }
You are missing a comma in here

2024-12-10 14:10 UTC, Albermonte commented on public/validators/main-albatross/NQ51 7BS3 0HVH 9R5M TUDH C5PG 490G S7XT KD4D.json
> +  }
You are missing a comma here too

2024-12-11 14:32 UTC, Albermonte commented
Check lint pls

2024-12-13 22:30 UTC, onmax commented
LGTM, @NimiqToolbox please let us know when we can merge it :) 

Thanks

2024-12-15 21:39 UTC, Julien59247787 commented
Hello Max

This should be good for the 2 json of the 2 delegates!

Sorry for the inconvenience and the time spent

Ju


De : Max ***@***.***>
Envoyé : vendredi 13 décembre 2024 23:30
À : nimiq/validators-api ***@***.***>
Cc : Julien CURTO ***@***.***>; Author ***@***.***>
Objet : Re: [nimiq/validators-api] add FRENCH NIMIQ VALIDATOR by Ju #1 & #2 (PR #75)


LGTM, @NimiqToolbox<https://github.com/NimiqToolbox> please let us know when we can merge it :)

Thanks

—
Reply to this email directly, view it on GitHub<https://github.com/nimiq/validators-api/pull/75#issuecomment-2542485255>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AETGI673FNLMYYBEREXN5G32FNNYJAVCNFSM6AAAAABS6NUKXGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBSGQ4DKMRVGU>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2024-12-23 19:23 UTC, Julien59247787 commented
hey 👋 

Is it OK to merge now ?

thanks 

Happy Christmas ! 🎄 🎅

2024-12-23 19:33 UTC, Albermonte approved these changes

2024-12-26 22:22 UTC, Julien59247787 commented
hey @Albermonte 👋 
Could you do something to speed up the "NimiqToolbox" review plz ?

Thank you very much

Ju

2024-12-27 19:52 UTC, Albermonte approved these changes

2024-12-27 19:52 UTC, merged